spring:
  liquibase:
    change-log: classpath:db/master.xml
  mail:
    host: smtp.yandex.ru
    port: 465
    protocol: smtps
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
  datasource:
    url: jdbc:postgresql://localhost:5432/events_db
    username: postgres
    password: postgres
    hikari:
      schema: events_schema
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS events_schema
      connection-timeout: 10000
  jpa:
    generate-ddl: false
    open-in-view: false
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false # Set to true in production
    servlet:
      content-type: text/html
  mvc:
    static-path-pattern: /**
  web:
    resources:
      static-locations: classpath:/static/,classpath:/public/

  app:
    upload:
      dir: uploads
      max-file-size: 10MB
      max-request-size: 10MB

  spring:
    servlet:
      multipart:
        max-file-size: 10MB
        max-request-size: 10MB